# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trousse_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trousse_App
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleSignIn'
  pod 'PromisesSwift', '~> 1.2.7'

  target 'Trousse_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Trousse_AppUITests' do
    # Pods for testing
  end

end
